In [9]:
import pandas as pd

In [10]:
df=pd.read_csv("ecommerce_delivery_report.csv")

In [11]:
df.head()

,Order ID,Customer ID,Platform,Delivery Time (Minutes),Product Category,Order Value (INR),Customer Feedback,Service Rating,Delivery Delay,Refund Requested
0,ORD000001,CUST2824,JioMart,30,Fruits & Vegetables,382,"Fast delivery, great service!",5,No,No
1,ORD000002,CUST1409,Blinkit,16,Dairy,279,Quick and reliable!,5,No,No
2,ORD000003,CUST5506,JioMart,25,Beverages,599,Items missing from order.,2,No,Yes
3,ORD000004,CUST5012,JioMart,42,Beverages,946,Items missing from order.,2,Yes,Yes
4,ORD000005,CUST4657,Blinkit,30,Beverages,334,"Fast delivery, great service!",5,No,No

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 10 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   Order ID                 100000 non-null  object
 1   Customer ID              100000 non-null  object
 2   Platform                 100000 non-null  object
 3   Delivery Time (Minutes)  100000 non-null  int64
 4   Product Category         100000 non-null  object
 5   Order Value (INR)        100000 non-null  int64
 6   Customer Feedback        100000 non-null  object
 7   Service Rating           100000 non-null  int64
 8   Delivery Delay           100000 non-null  object
 9   Refund Requested         100000 non-null  object
dtypes: int64(3), object(7)
memory usage: 7.6+ MB

In [13]:
df.describe(include="all")

,Order ID,Customer ID,Platform,Delivery Time (Minutes),Product Category,Order Value (INR),Customer Feedback,Service Rating,Delivery Delay,Refund Requested
count,100000,100000,100000,100000.000000,100000,100000.000000,100000,100000.000000,100000,100000
unique,100000,9000,3,NaN,6,NaN,13,NaN,2,2
top,ORD000001,CUST8779,Swiggy Instamart,NaN,Dairy,NaN,"Easy to order, loved it!",NaN,No,No
freq,1,26,33449,NaN,16857,NaN,7791,NaN,86328,54181
mean,NaN,NaN,NaN,29.536140,NaN,590.994400,NaN,3.240790,NaN,NaN
std,NaN,NaN,NaN,9.958933,NaN,417.409058,NaN,1.575962,NaN,NaN
min,NaN,NaN,NaN,5.000000,NaN,50.000000,NaN,1.000000,NaN,NaN
25%,NaN,NaN,NaN,23.000000,NaN,283.000000,NaN,2.000000,NaN,NaN
50%,NaN,NaN,NaN,30.000000,NaN,481.000000,NaN,3.000000,NaN,NaN
75%,NaN,NaN,NaN,36.000000,NaN,770.000000,NaN,5.000000,NaN,NaN
max,NaN,NaN,NaN,76.000000,NaN,2000.000000,NaN,5.000000,NaN,NaN

In [14]:
df.isnull().sum()

Order ID                   0
Customer ID                0
Platform                   0
Delivery Time (Minutes)    0
Product Category           0
Order Value (INR)          0
Customer Feedback          0
Service Rating             0
Delivery Delay             0
Refund Requested           0
dtype: int64

In [15]:
df.columns=df.columns.str.lower()
df.columns=df.columns.str.replace(' ','_')
df=df.rename(columns={'delivery_time_(minutes)':'delivery_time' ,'order_value_(inr)':'order_value'})

In [16]:
df.columns

Index(['order_id', 'customer_id', 'platform', 'delivery_time',
       'product_category', 'order_value', 'customer_feedback',
       'service_rating', 'delivery_delay', 'refund_requested'],
      dtype='object')

In [17]:
#column name cleaned
#there is no null value

In [18]:
#exporting data to mysql

from sqlalchemy import create_engine
from urllib.parse import quote_plus

password = quote_plus("rohan123@")

engine = create_engine(
    f"mysql+pymysql://root:{password}@localhost:3306/ecommerce_delivery"
)

df.to_sql("ecommerce", engine, if_exists="replace", index=False)

100000

In [19]:
pd.read_sql("SELECT * FROM ecommerce LIMIT 5;", engine)

,order_id,customer_id,platform,delivery_time,product_category,order_value,customer_feedback,service_rating,delivery_delay,refund_requested
0,ORD000001,CUST2824,JioMart,30,Fruits & Vegetables,382,"Fast delivery, great service!",5,No,No
1,ORD000002,CUST1409,Blinkit,16,Dairy,279,Quick and reliable!,5,No,No
2,ORD000003,CUST5506,JioMart,25,Beverages,599,Items missing from order.,2,No,Yes
3,ORD000004,CUST5012,JioMart,42,Beverages,946,Items missing from order.,2,Yes,Yes
4,ORD000005,CUST4657,Blinkit,30,Beverages,334,"Fast delivery, great service!",5,No,No